// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "alla/db-service/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AlchemyRepoInterface is an autogenerated mock type for the AlchemyRepoInterface type
type AlchemyRepoInterface struct {
	mock.Mock
}

// AddIngredients provides a mock function with given fields: ctx, ID, quantity
func (_m *AlchemyRepoInterface) AddIngredients(ctx context.Context, ID int, quantity int) error {
	ret := _m.Called(ctx, ID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddIngredients")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, ID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckExistRecipeByName provides a mock function with given fields: ctx, name
func (_m *AlchemyRepoInterface) CheckExistRecipeByName(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CheckExistRecipeByName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckIngredientExistsByName provides a mock function with given fields: ctx, name
func (_m *AlchemyRepoInterface) CheckIngredientExistsByName(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CheckIngredientExistsByName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckingIngridients provides a mock function with given fields: ctx, ings
func (_m *AlchemyRepoInterface) CheckingIngridients(ctx context.Context, ings []models.RecipeIngredients) error {
	ret := _m.Called(ctx, ings)

	if len(ret) == 0 {
		panic("no return value specified for CheckingIngridients")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.RecipeIngredients) error); ok {
		r0 = rf(ctx, ings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRecipe provides a mock function with given fields: ctx, m
func (_m *AlchemyRepoInterface) CreateRecipe(ctx context.Context, m *models.Recipe) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Recipe) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRecipeIngredients provides a mock function with given fields: ctx, valueString, valueArgs
func (_m *AlchemyRepoInterface) CreateRecipeIngredients(ctx context.Context, valueString []string, valueArgs []interface{}) error {
	ret := _m.Called(ctx, valueString, valueArgs)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipeIngredients")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []interface{}) error); ok {
		r0 = rf(ctx, valueString, valueArgs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBrewingTime provides a mock function with given fields: ctx, recipeId
func (_m *AlchemyRepoInterface) GetBrewingTime(ctx context.Context, recipeId int) (int, error) {
	ret := _m.Called(ctx, recipeId)

	if len(ret) == 0 {
		panic("no return value specified for GetBrewingTime")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, recipeId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, recipeId)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, recipeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIngredients provides a mock function with given fields: ctx
func (_m *AlchemyRepoInterface) GetIngredients(ctx context.Context) ([]models.Ingredient, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetIngredients")
	}

	var r0 []models.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Ingredient, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Ingredient); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ingredient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIngredientsByRecipe provides a mock function with given fields: ctx, recipeID
func (_m *AlchemyRepoInterface) GetIngredientsByRecipe(ctx context.Context, recipeID int) ([]models.RecipeIngredients, error) {
	ret := _m.Called(ctx, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for GetIngredientsByRecipe")
	}

	var r0 []models.RecipeIngredients
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.RecipeIngredients, error)); ok {
		return rf(ctx, recipeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.RecipeIngredients); ok {
		r0 = rf(ctx, recipeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RecipeIngredients)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, recipeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipeID provides a mock function with given fields: ctx, uuid
func (_m *AlchemyRepoInterface) GetRecipeID(ctx context.Context, uuid string) (int, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipeID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipes provides a mock function with given fields: ctx
func (_m *AlchemyRepoInterface) GetRecipes(ctx context.Context) ([]models.Recipe, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipes")
	}

	var r0 []models.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Recipe, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Recipe); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostIngredients provides a mock function with given fields: ctx, m
func (_m *AlchemyRepoInterface) PostIngredients(ctx context.Context, m models.Ingredient) (*models.Ingredient, error) {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for PostIngredients")
	}

	var r0 *models.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Ingredient) (*models.Ingredient, error)); ok {
		return rf(ctx, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Ingredient) *models.Ingredient); ok {
		r0 = rf(ctx, m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Ingredient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Ingredient) error); ok {
		r1 = rf(ctx, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAlchemyRepoInterface creates a new instance of AlchemyRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlchemyRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlchemyRepoInterface {
	mock := &AlchemyRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
