// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "alla/shared/DTO"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryBrewingInterface is an autogenerated mock type for the RepositoryBrewingInterface type
type RepositoryBrewingInterface struct {
	mock.Mock
}

// StartBrewing provides a mock function with given fields: _a0, _a1
func (_m *RepositoryBrewingInterface) StartBrewing(_a0 context.Context, _a1 dto.JobUUIDDTO) (*dto.JobTimeDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for StartBrewing")
	}

	var r0 *dto.JobTimeDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.JobUUIDDTO) (*dto.JobTimeDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.JobUUIDDTO) *dto.JobTimeDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JobTimeDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.JobUUIDDTO) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetStatus provides a mock function with given fields: _a0, _a1
func (_m *RepositoryBrewingInterface) SetStatus(_a0 context.Context, _a1 dto.JobStatusDTO) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.JobStatusDTO) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepositoryBrewingInterface creates a new instance of RepositoryBrewingInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryBrewingInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryBrewingInterface {
	mock := &RepositoryBrewingInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
