// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "alla/shared/DTO"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ServiceInterface is an autogenerated mock type for the ServiceInterface type
type ServiceInterface struct {
	mock.Mock
}

// AddIngredients provides a mock function with given fields: _a0, _a1
func (_m *ServiceInterface) AddIngredients(_a0 context.Context, _a1 dto.UpdateIngredientQuantityDTO) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddIngredients")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateIngredientQuantityDTO) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetIngredients provides a mock function with given fields: _a0
func (_m *ServiceInterface) GetIngredients(_a0 context.Context) ([]dto.IngredientResponseDTO, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetIngredients")
	}

	var r0 []dto.IngredientResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.IngredientResponseDTO, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.IngredientResponseDTO); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.IngredientResponseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipes provides a mock function with given fields: _a0
func (_m *ServiceInterface) GetRecipes(_a0 context.Context) ([]dto.RecipeResponseDTO, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipes")
	}

	var r0 []dto.RecipeResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.RecipeResponseDTO, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.RecipeResponseDTO); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.RecipeResponseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostIngredients provides a mock function with given fields: _a0, _a1
func (_m *ServiceInterface) PostIngredients(_a0 context.Context, _a1 dto.IngredientDTO) (*dto.IngredientResponseDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PostIngredients")
	}

	var r0 *dto.IngredientResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.IngredientDTO) (*dto.IngredientResponseDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.IngredientDTO) *dto.IngredientResponseDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.IngredientResponseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.IngredientDTO) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostRecipe provides a mock function with given fields: _a0, _a1
func (_m *ServiceInterface) PostRecipe(_a0 context.Context, _a1 dto.RecipeDTO) (*dto.RecipeResponseDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PostRecipe")
	}

	var r0 *dto.RecipeResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RecipeDTO) (*dto.RecipeResponseDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RecipeDTO) *dto.RecipeResponseDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RecipeResponseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RecipeDTO) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceInterface creates a new instance of ServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceInterface {
	mock := &ServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
