// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "alla/shared/DTO"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BrewingServiceInterface is an autogenerated mock type for the BrewingServiceInterface type
type BrewingServiceInterface struct {
	mock.Mock
}

// Boiled provides a mock function with given fields: ctx, JobUUIDDTO
func (_m *BrewingServiceInterface) Boiled(ctx context.Context, JobUUIDDTO *dto.JobUUIDDTO) error {
	ret := _m.Called(ctx, JobUUIDDTO)

	if len(ret) == 0 {
		panic("no return value specified for Boiled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.JobUUIDDTO) error); ok {
		r0 = rf(ctx, JobUUIDDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBrewStatus provides a mock function with given fields: ctx, JobUUIDDTO
func (_m *BrewingServiceInterface) GetBrewStatus(ctx context.Context, JobUUIDDTO dto.JobUUIDDTO) (*dto.JobStatusresponseDTO, error) {
	ret := _m.Called(ctx, JobUUIDDTO)

	if len(ret) == 0 {
		panic("no return value specified for GetBrewStatus")
	}

	var r0 *dto.JobStatusresponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.JobUUIDDTO) (*dto.JobStatusresponseDTO, error)); ok {
		return rf(ctx, JobUUIDDTO)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.JobUUIDDTO) *dto.JobStatusresponseDTO); ok {
		r0 = rf(ctx, JobUUIDDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JobStatusresponseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.JobUUIDDTO) error); ok {
		r1 = rf(ctx, JobUUIDDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostJob provides a mock function with given fields: ctx, jobDTO
func (_m *BrewingServiceInterface) PostJob(ctx context.Context, jobDTO dto.JobDTO) (*dto.JobUUIDDTO, error) {
	ret := _m.Called(ctx, jobDTO)

	if len(ret) == 0 {
		panic("no return value specified for PostJob")
	}

	var r0 *dto.JobUUIDDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.JobDTO) (*dto.JobUUIDDTO, error)); ok {
		return rf(ctx, jobDTO)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.JobDTO) *dto.JobUUIDDTO); ok {
		r0 = rf(ctx, jobDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JobUUIDDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.JobDTO) error); ok {
		r1 = rf(ctx, jobDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBrewingServiceInterface creates a new instance of BrewingServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrewingServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrewingServiceInterface {
	mock := &BrewingServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
