// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "alchemicallabaratory/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GrimoireRepoInterface is an autogenerated mock type for the GrimoireRepoInterface type
type GrimoireRepoInterface struct {
	mock.Mock
}

// AddIngredients provides a mock function with given fields: ctx, id, quantity
func (_m *GrimoireRepoInterface) AddIngredients(ctx context.Context, id int, quantity int) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddIngredients")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBrewStatus provides a mock function with given fields: ctx, uuid
func (_m *GrimoireRepoInterface) GetBrewStatus(ctx context.Context, uuid string) (string, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetBrewStatus")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIngredients provides a mock function with given fields: ctx
func (_m *GrimoireRepoInterface) GetIngredients(ctx context.Context) ([]models.Ingredient, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetIngredients")
	}

	var r0 []models.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Ingredient, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Ingredient); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ingredient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobByUUID provides a mock function with given fields: ctx, uuid
func (_m *GrimoireRepoInterface) GetJobByUUID(ctx context.Context, uuid string) (int, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetJobByUUID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipes provides a mock function with given fields: ctx
func (_m *GrimoireRepoInterface) GetRecipes(ctx context.Context) ([]models.Recipe, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipes")
	}

	var r0 []models.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Recipe, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Recipe); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostIngredients provides a mock function with given fields: ctx, m
func (_m *GrimoireRepoInterface) PostIngredients(ctx context.Context, m models.Ingredient) (*models.Ingredient, error) {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for PostIngredients")
	}

	var r0 *models.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Ingredient) (*models.Ingredient, error)); ok {
		return rf(ctx, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Ingredient) *models.Ingredient); ok {
		r0 = rf(ctx, m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Ingredient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Ingredient) error); ok {
		r1 = rf(ctx, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostJob provides a mock function with given fields: ctx, m
func (_m *GrimoireRepoInterface) PostJob(ctx context.Context, m models.BrewingJobs) (*models.BrewingJobs, error) {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for PostJob")
	}

	var r0 *models.BrewingJobs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.BrewingJobs) (*models.BrewingJobs, error)); ok {
		return rf(ctx, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.BrewingJobs) *models.BrewingJobs); ok {
		r0 = rf(ctx, m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BrewingJobs)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.BrewingJobs) error); ok {
		r1 = rf(ctx, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostRecipe provides a mock function with given fields: ctx, m
func (_m *GrimoireRepoInterface) PostRecipe(ctx context.Context, m models.Recipe) (*models.Recipe, error) {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for PostRecipe")
	}

	var r0 *models.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Recipe) (*models.Recipe, error)); ok {
		return rf(ctx, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Recipe) *models.Recipe); ok {
		r0 = rf(ctx, m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Recipe) error); ok {
		r1 = rf(ctx, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetStatus provides a mock function with given fields: ctx, uuid, status
func (_m *GrimoireRepoInterface) SetStatus(ctx context.Context, uuid string, status string) error {
	ret := _m.Called(ctx, uuid, status)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, uuid, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGrimoireRepoInterface creates a new instance of GrimoireRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGrimoireRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GrimoireRepoInterface {
	mock := &GrimoireRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
