// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: shared/proto/laboratory.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngredientService_CreateIngredient_FullMethodName = "/laboratory.IngredientService/CreateIngredient"
	IngredientService_GetIngredients_FullMethodName   = "/laboratory.IngredientService/GetIngredients"
	IngredientService_AddIngredient_FullMethodName    = "/laboratory.IngredientService/AddIngredient"
)

// IngredientServiceClient is the client API for IngredientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngredientServiceClient interface {
	CreateIngredient(ctx context.Context, in *CreateIngredientRequest, opts ...grpc.CallOption) (*IngredientResponse, error)
	GetIngredients(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IngredientListResponse, error)
	AddIngredient(ctx context.Context, in *AddIngredientRequest, opts ...grpc.CallOption) (*Empty, error)
}

type ingredientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngredientServiceClient(cc grpc.ClientConnInterface) IngredientServiceClient {
	return &ingredientServiceClient{cc}
}

func (c *ingredientServiceClient) CreateIngredient(ctx context.Context, in *CreateIngredientRequest, opts ...grpc.CallOption) (*IngredientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngredientResponse)
	err := c.cc.Invoke(ctx, IngredientService_CreateIngredient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingredientServiceClient) GetIngredients(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IngredientListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngredientListResponse)
	err := c.cc.Invoke(ctx, IngredientService_GetIngredients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingredientServiceClient) AddIngredient(ctx context.Context, in *AddIngredientRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, IngredientService_AddIngredient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngredientServiceServer is the server API for IngredientService service.
// All implementations must embed UnimplementedIngredientServiceServer
// for forward compatibility.
type IngredientServiceServer interface {
	CreateIngredient(context.Context, *CreateIngredientRequest) (*IngredientResponse, error)
	GetIngredients(context.Context, *Empty) (*IngredientListResponse, error)
	AddIngredient(context.Context, *AddIngredientRequest) (*Empty, error)
	mustEmbedUnimplementedIngredientServiceServer()
}

// UnimplementedIngredientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngredientServiceServer struct{}

func (UnimplementedIngredientServiceServer) CreateIngredient(context.Context, *CreateIngredientRequest) (*IngredientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIngredient not implemented")
}
func (UnimplementedIngredientServiceServer) GetIngredients(context.Context, *Empty) (*IngredientListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIngredients not implemented")
}
func (UnimplementedIngredientServiceServer) AddIngredient(context.Context, *AddIngredientRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIngredient not implemented")
}
func (UnimplementedIngredientServiceServer) mustEmbedUnimplementedIngredientServiceServer() {}
func (UnimplementedIngredientServiceServer) testEmbeddedByValue()                           {}

// UnsafeIngredientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngredientServiceServer will
// result in compilation errors.
type UnsafeIngredientServiceServer interface {
	mustEmbedUnimplementedIngredientServiceServer()
}

func RegisterIngredientServiceServer(s grpc.ServiceRegistrar, srv IngredientServiceServer) {
	// If the following call panics, it indicates UnimplementedIngredientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngredientService_ServiceDesc, srv)
}

func _IngredientService_CreateIngredient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIngredientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngredientServiceServer).CreateIngredient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngredientService_CreateIngredient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngredientServiceServer).CreateIngredient(ctx, req.(*CreateIngredientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngredientService_GetIngredients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngredientServiceServer).GetIngredients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngredientService_GetIngredients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngredientServiceServer).GetIngredients(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngredientService_AddIngredient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIngredientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngredientServiceServer).AddIngredient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngredientService_AddIngredient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngredientServiceServer).AddIngredient(ctx, req.(*AddIngredientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IngredientService_ServiceDesc is the grpc.ServiceDesc for IngredientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngredientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "laboratory.IngredientService",
	HandlerType: (*IngredientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIngredient",
			Handler:    _IngredientService_CreateIngredient_Handler,
		},
		{
			MethodName: "GetIngredients",
			Handler:    _IngredientService_GetIngredients_Handler,
		},
		{
			MethodName: "AddIngredient",
			Handler:    _IngredientService_AddIngredient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/laboratory.proto",
}

const (
	RecipesService_CreateRecipe_FullMethodName = "/laboratory.RecipesService/CreateRecipe"
	RecipesService_GetRecipes_FullMethodName   = "/laboratory.RecipesService/GetRecipes"
)

// RecipesServiceClient is the client API for RecipesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecipesServiceClient interface {
	CreateRecipe(ctx context.Context, in *PostRecipeRequest, opts ...grpc.CallOption) (*RecipeResponse, error)
	GetRecipes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RecipeListResponse, error)
}

type recipesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecipesServiceClient(cc grpc.ClientConnInterface) RecipesServiceClient {
	return &recipesServiceClient{cc}
}

func (c *recipesServiceClient) CreateRecipe(ctx context.Context, in *PostRecipeRequest, opts ...grpc.CallOption) (*RecipeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecipeResponse)
	err := c.cc.Invoke(ctx, RecipesService_CreateRecipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipesServiceClient) GetRecipes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RecipeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecipeListResponse)
	err := c.cc.Invoke(ctx, RecipesService_GetRecipes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecipesServiceServer is the server API for RecipesService service.
// All implementations must embed UnimplementedRecipesServiceServer
// for forward compatibility.
type RecipesServiceServer interface {
	CreateRecipe(context.Context, *PostRecipeRequest) (*RecipeResponse, error)
	GetRecipes(context.Context, *Empty) (*RecipeListResponse, error)
	mustEmbedUnimplementedRecipesServiceServer()
}

// UnimplementedRecipesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecipesServiceServer struct{}

func (UnimplementedRecipesServiceServer) CreateRecipe(context.Context, *PostRecipeRequest) (*RecipeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRecipe not implemented")
}
func (UnimplementedRecipesServiceServer) GetRecipes(context.Context, *Empty) (*RecipeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecipes not implemented")
}
func (UnimplementedRecipesServiceServer) mustEmbedUnimplementedRecipesServiceServer() {}
func (UnimplementedRecipesServiceServer) testEmbeddedByValue()                        {}

// UnsafeRecipesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecipesServiceServer will
// result in compilation errors.
type UnsafeRecipesServiceServer interface {
	mustEmbedUnimplementedRecipesServiceServer()
}

func RegisterRecipesServiceServer(s grpc.ServiceRegistrar, srv RecipesServiceServer) {
	// If the following call panics, it indicates UnimplementedRecipesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecipesService_ServiceDesc, srv)
}

func _RecipesService_CreateRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipesServiceServer).CreateRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipesService_CreateRecipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipesServiceServer).CreateRecipe(ctx, req.(*PostRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipesService_GetRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipesServiceServer).GetRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipesService_GetRecipes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipesServiceServer).GetRecipes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RecipesService_ServiceDesc is the grpc.ServiceDesc for RecipesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecipesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "laboratory.RecipesService",
	HandlerType: (*RecipesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRecipe",
			Handler:    _RecipesService_CreateRecipe_Handler,
		},
		{
			MethodName: "GetRecipes",
			Handler:    _RecipesService_GetRecipes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/laboratory.proto",
}
