// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shared/proto/laboratory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{0}
}

type CreateIngredientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIngredientRequest) Reset() {
	*x = CreateIngredientRequest{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngredientRequest) ProtoMessage() {}

func (x *CreateIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngredientRequest.ProtoReflect.Descriptor instead.
func (*CreateIngredientRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIngredientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateIngredientRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIngredientRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type IngredientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngredientResponse) Reset() {
	*x = IngredientResponse{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngredientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientResponse) ProtoMessage() {}

func (x *IngredientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngredientResponse.ProtoReflect.Descriptor instead.
func (*IngredientResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{2}
}

func (x *IngredientResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IngredientResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IngredientResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IngredientResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type IngredientListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ingredietns   []*IngredientResponse  `protobuf:"bytes,1,rep,name=ingredietns,proto3" json:"ingredietns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngredientListResponse) Reset() {
	*x = IngredientListResponse{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngredientListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientListResponse) ProtoMessage() {}

func (x *IngredientListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngredientListResponse.ProtoReflect.Descriptor instead.
func (*IngredientListResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{3}
}

func (x *IngredientListResponse) GetIngredietns() []*IngredientResponse {
	if x != nil {
		return x.Ingredietns
	}
	return nil
}

type AddIngredientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddIngredientRequest) Reset() {
	*x = AddIngredientRequest{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIngredientRequest) ProtoMessage() {}

func (x *AddIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIngredientRequest.ProtoReflect.Descriptor instead.
func (*AddIngredientRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{4}
}

func (x *AddIngredientRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddIngredientRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// recipes
type RecipeIngredients struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IngredietnID    int32                  `protobuf:"varint,1,opt,name=ingredietnID,proto3" json:"ingredietnID,omitempty"`
	QueuntityNeeded int32                  `protobuf:"varint,2,opt,name=queuntityNeeded,proto3" json:"queuntityNeeded,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecipeIngredients) Reset() {
	*x = RecipeIngredients{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeIngredients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeIngredients) ProtoMessage() {}

func (x *RecipeIngredients) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeIngredients.ProtoReflect.Descriptor instead.
func (*RecipeIngredients) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{5}
}

func (x *RecipeIngredients) GetIngredietnID() int32 {
	if x != nil {
		return x.IngredietnID
	}
	return 0
}

func (x *RecipeIngredients) GetQueuntityNeeded() int32 {
	if x != nil {
		return x.QueuntityNeeded
	}
	return 0
}

type PostRecipeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	BrewingTimeSeconds int32                  `protobuf:"varint,3,opt,name=brewingTimeSeconds,proto3" json:"brewingTimeSeconds,omitempty"`
	RecIngs            []*RecipeIngredients   `protobuf:"bytes,4,rep,name=recIngs,proto3" json:"recIngs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PostRecipeRequest) Reset() {
	*x = PostRecipeRequest{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRecipeRequest) ProtoMessage() {}

func (x *PostRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRecipeRequest.ProtoReflect.Descriptor instead.
func (*PostRecipeRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{6}
}

func (x *PostRecipeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostRecipeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PostRecipeRequest) GetBrewingTimeSeconds() int32 {
	if x != nil {
		return x.BrewingTimeSeconds
	}
	return 0
}

func (x *PostRecipeRequest) GetRecIngs() []*RecipeIngredients {
	if x != nil {
		return x.RecIngs
	}
	return nil
}

type RecipeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	BrewingTimeSeconds int32                  `protobuf:"varint,4,opt,name=brewingTimeSeconds,proto3" json:"brewingTimeSeconds,omitempty"`
	RecIngs            []*RecipeIngredients   `protobuf:"bytes,5,rep,name=recIngs,proto3" json:"recIngs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecipeResponse) Reset() {
	*x = RecipeResponse{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeResponse) ProtoMessage() {}

func (x *RecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeResponse.ProtoReflect.Descriptor instead.
func (*RecipeResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{7}
}

func (x *RecipeResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecipeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecipeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecipeResponse) GetBrewingTimeSeconds() int32 {
	if x != nil {
		return x.BrewingTimeSeconds
	}
	return 0
}

func (x *RecipeResponse) GetRecIngs() []*RecipeIngredients {
	if x != nil {
		return x.RecIngs
	}
	return nil
}

type RecipeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipes       []*RecipeResponse      `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeListResponse) Reset() {
	*x = RecipeListResponse{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeListResponse) ProtoMessage() {}

func (x *RecipeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeListResponse.ProtoReflect.Descriptor instead.
func (*RecipeListResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{8}
}

func (x *RecipeListResponse) GetRecipes() []*RecipeResponse {
	if x != nil {
		return x.Recipes
	}
	return nil
}

type PostJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      int32                  `protobuf:"varint,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostJobRequest) Reset() {
	*x = PostJobRequest{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostJobRequest) ProtoMessage() {}

func (x *PostJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostJobRequest.ProtoReflect.Descriptor instead.
func (*PostJobRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{9}
}

func (x *PostJobRequest) GetRecipeId() int32 {
	if x != nil {
		return x.RecipeId
	}
	return 0
}

func (x *PostJobRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type JobUUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobUUID       string                 `protobuf:"bytes,1,opt,name=jobUUID,proto3" json:"jobUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobUUID) Reset() {
	*x = JobUUID{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobUUID) ProtoMessage() {}

func (x *JobUUID) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobUUID.ProtoReflect.Descriptor instead.
func (*JobUUID) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{10}
}

func (x *JobUUID) GetJobUUID() string {
	if x != nil {
		return x.JobUUID
	}
	return ""
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{11}
}

func (x *JobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ChangeJobStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeJobStatus) Reset() {
	*x = ChangeJobStatus{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeJobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeJobStatus) ProtoMessage() {}

func (x *ChangeJobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeJobStatus.ProtoReflect.Descriptor instead.
func (*ChangeJobStatus) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeJobStatus) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ChangeJobStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type JobTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrewingTime   int32                  `protobuf:"varint,1,opt,name=brewingTime,proto3" json:"brewingTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobTime) Reset() {
	*x = JobTime{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobTime) ProtoMessage() {}

func (x *JobTime) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobTime.ProtoReflect.Descriptor instead.
func (*JobTime) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{13}
}

func (x *JobTime) GetBrewingTime() int32 {
	if x != nil {
		return x.BrewingTime
	}
	return 0
}

var File_shared_proto_laboratory_proto protoreflect.FileDescriptor

const file_shared_proto_laboratory_proto_rawDesc = "" +
	"\n" +
	"\x1dshared/proto/laboratory.proto\x12\n" +
	"laboratory\"\a\n" +
	"\x05Empty\"k\n" +
	"\x17CreateIngredientRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"v\n" +
	"\x12IngredientResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"Z\n" +
	"\x16IngredientListResponse\x12@\n" +
	"\vingredietns\x18\x01 \x03(\v2\x1e.laboratory.IngredientResponseR\vingredietns\"B\n" +
	"\x14AddIngredientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"a\n" +
	"\x11RecipeIngredients\x12\"\n" +
	"\fingredietnID\x18\x01 \x01(\x05R\fingredietnID\x12(\n" +
	"\x0fqueuntityNeeded\x18\x02 \x01(\x05R\x0fqueuntityNeeded\"\xb2\x01\n" +
	"\x11PostRecipeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12.\n" +
	"\x12brewingTimeSeconds\x18\x03 \x01(\x05R\x12brewingTimeSeconds\x127\n" +
	"\arecIngs\x18\x04 \x03(\v2\x1d.laboratory.RecipeIngredientsR\arecIngs\"\xbf\x01\n" +
	"\x0eRecipeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\x12brewingTimeSeconds\x18\x04 \x01(\x05R\x12brewingTimeSeconds\x127\n" +
	"\arecIngs\x18\x05 \x03(\v2\x1d.laboratory.RecipeIngredientsR\arecIngs\"J\n" +
	"\x12RecipeListResponse\x124\n" +
	"\arecipes\x18\x01 \x03(\v2\x1a.laboratory.RecipeResponseR\arecipes\"F\n" +
	"\x0ePostJobRequest\x12\x1a\n" +
	"\brecipeId\x18\x01 \x01(\x05R\brecipeId\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails\"#\n" +
	"\aJobUUID\x12\x18\n" +
	"\ajobUUID\x18\x01 \x01(\tR\ajobUUID\"+\n" +
	"\x11JobStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"=\n" +
	"\x0fChangeJobStatus\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"+\n" +
	"\aJobTime\x12 \n" +
	"\vbrewingTime\x18\x01 \x01(\x05R\vbrewingTime2\xfb\x01\n" +
	"\x11IngredientService\x12W\n" +
	"\x10CreateIngredient\x12#.laboratory.CreateIngredientRequest\x1a\x1e.laboratory.IngredientResponse\x12G\n" +
	"\x0eGetIngredients\x12\x11.laboratory.Empty\x1a\".laboratory.IngredientListResponse\x12D\n" +
	"\rAddIngredient\x12 .laboratory.AddIngredientRequest\x1a\x11.laboratory.Empty2\x9c\x01\n" +
	"\x0eRecipesService\x12I\n" +
	"\fCreateRecipe\x12\x1d.laboratory.PostRecipeRequest\x1a\x1a.laboratory.RecipeResponse\x12?\n" +
	"\n" +
	"GetRecipes\x12\x11.laboratory.Empty\x1a\x1e.laboratory.RecipeListResponse2\x87\x02\n" +
	"\n" +
	"JobService\x12:\n" +
	"\aPostJob\x12\x1a.laboratory.PostJobRequest\x1a\x13.laboratory.JobUUID\x12C\n" +
	"\rGetBrewStatus\x12\x13.laboratory.JobUUID\x1a\x1d.laboratory.JobStatusResponse\x12>\n" +
	"\fChangeStatus\x12\x1b.laboratory.ChangeJobStatus\x1a\x11.laboratory.Empty\x128\n" +
	"\fStartBrewing\x12\x13.laboratory.JobUUID\x1a\x13.laboratory.JobTime2=\n" +
	"\vBrewService\x12.\n" +
	"\x04Brew\x12\x13.laboratory.JobUUID\x1a\x11.laboratory.EmptyB\vZ\tshared/pbb\x06proto3"

var (
	file_shared_proto_laboratory_proto_rawDescOnce sync.Once
	file_shared_proto_laboratory_proto_rawDescData []byte
)

func file_shared_proto_laboratory_proto_rawDescGZIP() []byte {
	file_shared_proto_laboratory_proto_rawDescOnce.Do(func() {
		file_shared_proto_laboratory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_laboratory_proto_rawDesc), len(file_shared_proto_laboratory_proto_rawDesc)))
	})
	return file_shared_proto_laboratory_proto_rawDescData
}

var file_shared_proto_laboratory_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_shared_proto_laboratory_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: laboratory.Empty
	(*CreateIngredientRequest)(nil), // 1: laboratory.CreateIngredientRequest
	(*IngredientResponse)(nil),      // 2: laboratory.IngredientResponse
	(*IngredientListResponse)(nil),  // 3: laboratory.IngredientListResponse
	(*AddIngredientRequest)(nil),    // 4: laboratory.AddIngredientRequest
	(*RecipeIngredients)(nil),       // 5: laboratory.RecipeIngredients
	(*PostRecipeRequest)(nil),       // 6: laboratory.PostRecipeRequest
	(*RecipeResponse)(nil),          // 7: laboratory.RecipeResponse
	(*RecipeListResponse)(nil),      // 8: laboratory.RecipeListResponse
	(*PostJobRequest)(nil),          // 9: laboratory.PostJobRequest
	(*JobUUID)(nil),                 // 10: laboratory.JobUUID
	(*JobStatusResponse)(nil),       // 11: laboratory.JobStatusResponse
	(*ChangeJobStatus)(nil),         // 12: laboratory.ChangeJobStatus
	(*JobTime)(nil),                 // 13: laboratory.JobTime
}
var file_shared_proto_laboratory_proto_depIdxs = []int32{
	2,  // 0: laboratory.IngredientListResponse.ingredietns:type_name -> laboratory.IngredientResponse
	5,  // 1: laboratory.PostRecipeRequest.recIngs:type_name -> laboratory.RecipeIngredients
	5,  // 2: laboratory.RecipeResponse.recIngs:type_name -> laboratory.RecipeIngredients
	7,  // 3: laboratory.RecipeListResponse.recipes:type_name -> laboratory.RecipeResponse
	1,  // 4: laboratory.IngredientService.CreateIngredient:input_type -> laboratory.CreateIngredientRequest
	0,  // 5: laboratory.IngredientService.GetIngredients:input_type -> laboratory.Empty
	4,  // 6: laboratory.IngredientService.AddIngredient:input_type -> laboratory.AddIngredientRequest
	6,  // 7: laboratory.RecipesService.CreateRecipe:input_type -> laboratory.PostRecipeRequest
	0,  // 8: laboratory.RecipesService.GetRecipes:input_type -> laboratory.Empty
	9,  // 9: laboratory.JobService.PostJob:input_type -> laboratory.PostJobRequest
	10, // 10: laboratory.JobService.GetBrewStatus:input_type -> laboratory.JobUUID
	12, // 11: laboratory.JobService.ChangeStatus:input_type -> laboratory.ChangeJobStatus
	10, // 12: laboratory.JobService.StartBrewing:input_type -> laboratory.JobUUID
	10, // 13: laboratory.BrewService.Brew:input_type -> laboratory.JobUUID
	2,  // 14: laboratory.IngredientService.CreateIngredient:output_type -> laboratory.IngredientResponse
	3,  // 15: laboratory.IngredientService.GetIngredients:output_type -> laboratory.IngredientListResponse
	0,  // 16: laboratory.IngredientService.AddIngredient:output_type -> laboratory.Empty
	7,  // 17: laboratory.RecipesService.CreateRecipe:output_type -> laboratory.RecipeResponse
	8,  // 18: laboratory.RecipesService.GetRecipes:output_type -> laboratory.RecipeListResponse
	10, // 19: laboratory.JobService.PostJob:output_type -> laboratory.JobUUID
	11, // 20: laboratory.JobService.GetBrewStatus:output_type -> laboratory.JobStatusResponse
	0,  // 21: laboratory.JobService.ChangeStatus:output_type -> laboratory.Empty
	13, // 22: laboratory.JobService.StartBrewing:output_type -> laboratory.JobTime
	0,  // 23: laboratory.BrewService.Brew:output_type -> laboratory.Empty
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_shared_proto_laboratory_proto_init() }
func file_shared_proto_laboratory_proto_init() {
	if File_shared_proto_laboratory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_laboratory_proto_rawDesc), len(file_shared_proto_laboratory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_shared_proto_laboratory_proto_goTypes,
		DependencyIndexes: file_shared_proto_laboratory_proto_depIdxs,
		MessageInfos:      file_shared_proto_laboratory_proto_msgTypes,
	}.Build()
	File_shared_proto_laboratory_proto = out.File
	file_shared_proto_laboratory_proto_goTypes = nil
	file_shared_proto_laboratory_proto_depIdxs = nil
}
