// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shared/proto/laboratory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateIngredientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIngredientRequest) Reset() {
	*x = CreateIngredientRequest{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngredientRequest) ProtoMessage() {}

func (x *CreateIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngredientRequest.ProtoReflect.Descriptor instead.
func (*CreateIngredientRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIngredientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateIngredientRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIngredientRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type IngredientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngredientResponse) Reset() {
	*x = IngredientResponse{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngredientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientResponse) ProtoMessage() {}

func (x *IngredientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngredientResponse.ProtoReflect.Descriptor instead.
func (*IngredientResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{1}
}

func (x *IngredientResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IngredientResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IngredientResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IngredientResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type IngredientListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ingredietns   []*IngredientResponse  `protobuf:"bytes,1,rep,name=ingredietns,proto3" json:"ingredietns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngredientListResponse) Reset() {
	*x = IngredientListResponse{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngredientListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientListResponse) ProtoMessage() {}

func (x *IngredientListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngredientListResponse.ProtoReflect.Descriptor instead.
func (*IngredientListResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{2}
}

func (x *IngredientListResponse) GetIngredietns() []*IngredientResponse {
	if x != nil {
		return x.Ingredietns
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_shared_proto_laboratory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_laboratory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_shared_proto_laboratory_proto_rawDescGZIP(), []int{3}
}

var File_shared_proto_laboratory_proto protoreflect.FileDescriptor

const file_shared_proto_laboratory_proto_rawDesc = "" +
	"\n" +
	"\x1dshared/proto/laboratory.proto\x12\n" +
	"laboratory\"k\n" +
	"\x17CreateIngredientRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"v\n" +
	"\x12IngredientResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"Z\n" +
	"\x16IngredientListResponse\x12@\n" +
	"\vingredietns\x18\x01 \x03(\v2\x1e.laboratory.IngredientResponseR\vingredietns\"\a\n" +
	"\x05Empty2\xb5\x01\n" +
	"\x11IngredientService\x12W\n" +
	"\x10CreateIngredient\x12#.laboratory.CreateIngredientRequest\x1a\x1e.laboratory.IngredientResponse\x12G\n" +
	"\x0eGetIngredients\x12\x11.laboratory.Empty\x1a\".laboratory.IngredientListResponseB\vZ\tshared/pbb\x06proto3"

var (
	file_shared_proto_laboratory_proto_rawDescOnce sync.Once
	file_shared_proto_laboratory_proto_rawDescData []byte
)

func file_shared_proto_laboratory_proto_rawDescGZIP() []byte {
	file_shared_proto_laboratory_proto_rawDescOnce.Do(func() {
		file_shared_proto_laboratory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_laboratory_proto_rawDesc), len(file_shared_proto_laboratory_proto_rawDesc)))
	})
	return file_shared_proto_laboratory_proto_rawDescData
}

var file_shared_proto_laboratory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_proto_laboratory_proto_goTypes = []any{
	(*CreateIngredientRequest)(nil), // 0: laboratory.CreateIngredientRequest
	(*IngredientResponse)(nil),      // 1: laboratory.IngredientResponse
	(*IngredientListResponse)(nil),  // 2: laboratory.IngredientListResponse
	(*Empty)(nil),                   // 3: laboratory.Empty
}
var file_shared_proto_laboratory_proto_depIdxs = []int32{
	1, // 0: laboratory.IngredientListResponse.ingredietns:type_name -> laboratory.IngredientResponse
	0, // 1: laboratory.IngredientService.CreateIngredient:input_type -> laboratory.CreateIngredientRequest
	3, // 2: laboratory.IngredientService.GetIngredients:input_type -> laboratory.Empty
	1, // 3: laboratory.IngredientService.CreateIngredient:output_type -> laboratory.IngredientResponse
	2, // 4: laboratory.IngredientService.GetIngredients:output_type -> laboratory.IngredientListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_proto_laboratory_proto_init() }
func file_shared_proto_laboratory_proto_init() {
	if File_shared_proto_laboratory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_laboratory_proto_rawDesc), len(file_shared_proto_laboratory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_laboratory_proto_goTypes,
		DependencyIndexes: file_shared_proto_laboratory_proto_depIdxs,
		MessageInfos:      file_shared_proto_laboratory_proto_msgTypes,
	}.Build()
	File_shared_proto_laboratory_proto = out.File
	file_shared_proto_laboratory_proto_goTypes = nil
	file_shared_proto_laboratory_proto_depIdxs = nil
}
