// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "alla/db-service/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BrewingRepoInterface is an autogenerated mock type for the BrewingRepoInterface type
type BrewingRepoInterface struct {
	mock.Mock
}

// CreateJob provides a mock function with given fields: ctx, m
func (_m *BrewingRepoInterface) CreateJob(ctx context.Context, m *models.BrewingJobs) (*models.BrewingJobs, error) {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateJob")
	}

	var r0 *models.BrewingJobs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.BrewingJobs) (*models.BrewingJobs, error)); ok {
		return rf(ctx, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.BrewingJobs) *models.BrewingJobs); ok {
		r0 = rf(ctx, m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BrewingJobs)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.BrewingJobs) error); ok {
		r1 = rf(ctx, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBrewStatus provides a mock function with given fields: ctx, uuid
func (_m *BrewingRepoInterface) GetBrewStatus(ctx context.Context, uuid string) (string, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetBrewStatus")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetStatus provides a mock function with given fields: ctx, uuid, status
func (_m *BrewingRepoInterface) SetStatus(ctx context.Context, uuid string, status string) error {
	ret := _m.Called(ctx, uuid, status)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, uuid, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBrewingRepoInterface creates a new instance of BrewingRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrewingRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrewingRepoInterface {
	mock := &BrewingRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
