// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

// import (
// 	context "context"

// 	mock "github.com/stretchr/testify/mock"
// )

// // BoilerWorkerInterface is an autogenerated mock type for the BoilerWorkerInterface type
// type BoilerWorkerInterface struct {
// 	mock.Mock
// }

// // Boiled provides a mock function with given fields: ctx, uuid
// func (_m *BoilerWorkerInterface) Boiled(ctx context.Context, uuid string) error {
// 	ret := _m.Called(ctx, uuid)

// 	if len(ret) == 0 {
// 		panic("no return value specified for Boiled")
// 	}

// 	var r0 error
// 	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
// 		r0 = rf(ctx, uuid)
// 	} else {
// 		r0 = ret.Error(0)
// 	}

// 	return r0
// }

// // NewBoilerWorkerInterface creates a new instance of BoilerWorkerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// // The first argument is typically a *testing.T value.
// func NewBoilerWorkerInterface(t interface {
// 	mock.TestingT
// 	Cleanup(func())
// }) *BoilerWorkerInterface {
// 	mock := &BoilerWorkerInterface{}
// 	mock.Mock.Test(t)

// 	t.Cleanup(func() { mock.AssertExpectations(t) })

// 	return mock
// }
